import type { Paper } from './papers'

// Generated by scripts/extract-cs-capstone.py from the poster PDF.
// Bullets are the poster's own text; the poster carries no figure captions.
export const csCapstone: Paper = {
  "slug": "cs-capstone",
  "eyebrow": "CS Capstone",
  "title": "RevolutionParts Inc.: Quoting",
  "meta": [
    {
      "label": "Team",
      "value": "Daniel Chang, Nolan Gabaldon, Kian Javaheri, Haamid Juvale, Hillary Li"
    },
    {
      "label": "Sponsor",
      "value": "Rida Bazzi"
    },
    {
      "label": "Poster",
      "value": "CS/E - 180"
    }
  ],
  "actions": [
    {
      "label": "View Poster",
      "pdfSrc": "/pdfs/cs-capstone/cs-capstone.pdf"
    },
    {
      "label": "Watch Video",
      "href": "https://www.youtube.com/watch?v=qzW7qxQkHSs"
    }
  ],
  "sections": [
    {
      "id": "overview",
      "title": "Project Overview",
      "blocks": [
        {
          "type": "list",
          "items": [
            "Create an effective quoting functionality for shipments that replaces the existing quoting service–EasyPost–in RP’s codebase",
            "Create an effective caching mechanism that reduces API calls."
          ]
        }
      ]
    },
    {
      "id": "epic",
      "title": "EPIC and Customer Archetypes",
      "blocks": [
        {
          "type": "h3",
          "text": "EPIC"
        },
        {
          "type": "list",
          "items": [
            "Quoting",
            "Caching"
          ]
        },
        {
          "type": "h3",
          "text": "Customer Archetypes"
        },
        {
          "type": "list",
          "items": [
            "Autopart Buyers",
            "Autopart Suppliers",
            "Inventory Managers"
          ]
        }
      ]
    },
    {
      "id": "design",
      "title": "Design Description/Justification",
      "blocks": [
        {
          "type": "h3",
          "text": "Cache Creation"
        },
        {
          "type": "list",
          "items": [
            "We created a historical and refreshable cache that takes in data from a CSV file and loads into in PostgreSQL server and is queryable over HTTP."
          ]
        },
        {
          "type": "figure",
          "src": "/pdfs/cs-capstone/figure1.png",
          "width": 1595,
          "height": 861,
          "caption": ""
        },
        {
          "type": "figure",
          "src": "/pdfs/cs-capstone/figure2.png",
          "width": 2029,
          "height": 998,
          "caption": ""
        },
        {
          "type": "figure",
          "src": "/pdfs/cs-capstone/figure3.png",
          "width": 1656,
          "height": 626,
          "caption": ""
        }
      ]
    },
    {
      "id": "results",
      "title": "Results",
      "blocks": [
        {
          "type": "list",
          "items": [
            "Developed an intuitive interface tool to view different rates returned from API carriers based on package description",
            "Designed a backend server with API endpoints that forwards requests to the cache and then to carrier APIs if the cache missed",
            "Successfully retrieves address and data response from historical data/carrier APIs along with side-by-side delay times for cache hits and misses",
            "Implemented cache system for quicker responses, and less reliance on third-party API services."
          ]
        },
        {
          "type": "list",
          "items": [
            "More time to get a quote means less sales.",
            "Reduces cost of calling external APIs."
          ],
          "nested": true
        },
        {
          "type": "figure",
          "src": "/pdfs/cs-capstone/figure4.png",
          "width": 1937,
          "height": 1149,
          "caption": ""
        }
      ]
    },
    {
      "id": "value",
      "title": "Value for RP",
      "blocks": [
        {
          "type": "list",
          "items": [
            "Financial",
            "Customer Satisfication"
          ]
        }
      ]
    },
    {
      "id": "lessons",
      "title": "Lessons Learned",
      "blocks": [
        {
          "type": "list",
          "items": [
            "The importance of data analysis and problem understanding for caching",
            "Realistic expectations of project application in real world scenarios"
          ]
        }
      ]
    },
    {
      "id": "future",
      "title": "Future Work",
      "blocks": [
        {
          "type": "list",
          "items": [
            "Integrate API with RevolutionParts’ code base.",
            "Gain API credentials for UPS.",
            "Gain production API credentials for all carriers."
          ]
        }
      ]
    }
  ]
}
